##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/

# windowrule = float,class:^(kitty)$,title:^(kitty)$

windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
